version: '3.8'
services:
  db:
      image: postgres:alpine3.18
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: kanehuri//974
        POSTGRES_DB: covid-db
      ports:
        - "5432:5432"
  back: 
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
