version: '3.8'
services:
  back: 
      build:
        context: .
        dockerfile: dockerfile
      depends_on:
        - db
      links:
        - db
      ports:
        - "8080:8080"

  db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kanehuri//974
      POSTGRES_DB: covid-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
