version: '3.8'

services:
  covid-db:
    container_name: covid-db
    image: covid-db-fullstack
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - postgres-db
  postgres-db:
    container_name: 'postgres-db'
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
networks:
  default:
    name: covid-db-network
    driver: bridge