spring:
  liquibase:
    enabled: false
  datasource:
    url : jdbc:postgresql://postgres-db:5432/covid-db
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create
  security:
    user:
      name: Admin
      password: Administrateur
    basic:
      enabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
